#!./venv/bin/python
"""
Zero-shot semantic indexing CLI
"""

import os
import sys

from dynacli import main

# Yes you can define your own version here
__version__ = "1.0"

cwd = os.path.dirname(__file__)
# The list of the paths for searching packages and modules by DynaCLI
# This is a simplest possible configuration. Look at [TBD]() for complete list
# of configuration options and typical use cases for each one.
search_path = ["./zssi/utils"]
# This needs to be done only if your sys.path does not already include it
sys.path.extend(search_path)

main(search_path)
